# Generated by Django 2.2.4 on 2019-09-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(choices=[('the Brass Coast', 'the Brass Coast'), ('Dawn', 'Dawn'), ('Highguard', 'Highguard'), ('Imperial Orcs', 'Imperial Orcs'), ('the League', 'the League'), ('the Marches', 'the Marches'), ('Navarr', 'Navarr'), ('Urizen', 'Urizen'), ('Varushka', 'Varushka'), ('Wintermark', 'Wintermark'), ('Faraden', 'Faraden')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pronouns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(max_length=50)),
                ('accusative', models.CharField(max_length=50)),
                ('genitive', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SummitDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WriteupSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_for_narrative', to='core.Notes')),
                ('notes', models.ManyToManyField(related_name='section_for_notes', to='core.Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vision_for_account', to='core.WriteupSection')),
                ('commentaries', models.ManyToManyField(related_name='vision_for_commentaries', to='core.Notes')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SummitDate')),
                ('day_ritual', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vision_for_day_ritual', to='core.WriteupSection')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visions_as_guide', to='core.Person')),
                ('night_ritual', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vision_for_night_ritual', to='core.WriteupSection')),
                ('soul_statuses', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vision_for_soul_statuses', to='core.WriteupSection')),
                ('visionary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visions_as_visionary', to='core.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='pronouns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pronouns'),
        ),
    ]
