# Generated by Django 3.0.8 on 2020-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='number',
            field=models.CharField(default='<not set>', help_text='The volume number (e.g. 2a)', max_length=10),
        ),
    ]
