# Generated by Django 3.0.8 on 2020-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='date_season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], default='Winter', max_length=6),
        ),
    ]
