# Generated by Django 3.0.8 on 2020-08-16 14:45
import re

from django.db import migrations

VOLUME_NAME_RE = r"Volume (?P<number>\d[a-d]), (?P<season>\w+) (?P<fest>\w+) (?P<year>\d+) YE"

def convert_date_string_to_other_fields(apps, schema_editor):
    Volume = apps.get_model('core', 'Volume')
    for volume in Volume.objects.all():
        m = re.match(VOLUME_NAME_RE, str(volume.date))
        if m:
            fields = m.groupdict()
            volume.number = fields["number"]
            volume.date_season = fields["season"]
            # We don't need to set what festival it was (Equinox or Solstice), because
            # we can determine that from the season alone.
            volume.date_year = fields["year"]
            volume.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_volume_date_year'),
    ]

    operations = [
        migrations.RunPython(
            code=convert_date_string_to_other_fields,
            reverse_code=migrations.RunPython.noop)
    ]
