# Generated by Django 3.0.8 on 2020-08-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_date_string_to_other_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='date',
        ),
    ]
