# Generated by Django 3.0.8 on 2020-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_volume_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.CharField(help_text='The volume number (e.g. 2a)', max_length=10),
        ),
    ]
