# Generated by Django 3.0.8 on 2020-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_default_on_volume_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='date_year',
            field=models.IntegerField(),
        ),
    ]
