# Generated by Django 3.0.8 on 2020-08-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_default_on_volume_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='visionary',
            field=models.CharField(default='Abraxus Wulfricspire', max_length=200),
            preserve_default=False,
        ),
    ]
