# Generated by Django 3.0.8 on 2020-08-20 20:45

from django.db import migrations


def extract_visionary_name(apps, schema_editor):
    Vision = apps.get_model('core', 'Vision')
    for vision in Vision.objects.all():
        vision_lines = str(vision.account).splitlines()
        vision.visionary = vision_lines[0].lstrip("-").rstrip("-")
        vision.account = "\n".join(vision_lines[1:])
        vision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vision_visionary'),
    ]

    operations = [
        migrations.RunPython(
            code=extract_visionary_name,
            reverse_code=migrations.RunPython.noop)
    ]
