# Generated by Django 3.0.8 on 2020-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_extract_visionary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='guide',
            field=models.CharField(default='Wulfric Wulfricsson', max_length=200),
            preserve_default=False,
        ),
    ]
