# Generated by Django 3.0.8 on 2020-08-21 15:18

from django.db import migrations


def extract_guide_name(apps, schema_editor):
    Vision = apps.get_model('core', 'Vision')
    for vision in Vision.objects.all():
        vision_lines = str(vision.account).splitlines()
        # The line about the guide starts with "Accompanied by". Copy everything afterwards.
        vision.guide = vision_lines[0][len("Accompanied by "):]
        vision.account = "\n".join(vision_lines[1:])
        vision.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vision_guide'),
    ]

    operations = [
        migrations.RunPython(
            code=extract_guide_name,
            reverse_code=migrations.RunPython.noop)
    ]
