# Generated by Django 3.0.8 on 2020-08-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_extract_guide_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='dose_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
