# Generated by Django 3.0.8 on 2020-08-22 22:39

from django.db import migrations


def extract_dose_origin(apps, schema_editor):
    Vision = apps.get_model('core', 'Vision')
    for vision in Vision.objects.all():
        vision_lines = str(vision.account).splitlines()
        if "selected" in vision_lines[0]:
            vision.dose_origin = vision_lines[0]
            vision.account = "\n".join(vision_lines[1:]).lstrip("\r\n")
            vision.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vision_dose_origin'),
    ]

    operations = [
        migrations.RunPython(
            code=extract_dose_origin,
            reverse_code=migrations.RunPython.noop)
    ]
