# Generated by Django 3.1 on 2020-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vision_ritual_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='soul_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
