# Generated by Django 3.1 on 2020-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_make_dose_origin_longer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
