# Generated by Django 3.1 on 2020-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vision_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='ready_to_publish',
            field=models.BooleanField(default=False),
        ),
    ]
