# Generated by Django 3.1 on 2020-08-27 10:23

from django.db import migrations

def set_visions_as_ready_to_publish(apps, schema_editor):
    Vision = apps.get_model('core', 'Vision')
    for vision in Vision.objects.all():
        vision.ready_to_publish = True
        vision.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vision_ready_to_publish'),
    ]

    operations = [
        migrations.RunPython(
            code=set_visions_as_ready_to_publish,
            reverse_code=migrations.RunPython.noop)
    ]
