# Generated by Django 3.1 on 2020-09-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_set_existing_accounts_as_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='order_in_volume',
            field=models.IntegerField(default=0),
        ),
    ]
