# Generated by Django 3.1 on 2020-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_make_volume_and_order_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='account_attribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='commentary_attribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='notes_attribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
