# Generated by Django 3.1 on 2020-09-21 16:12

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_attribution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vision',
            name='account_writers',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='accounts_written_by', to='core.Writer'),
        ),
        migrations.AddField(
            model_name='vision',
            name='commentary_writers',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='commentary_written_by', to='core.Writer'),
        ),
        migrations.AddField(
            model_name='vision',
            name='notes_writers',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='notes_written_by', to='core.Writer'),
        ),
    ]
