# Generated by Django 3.1 on 2020-09-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_make_commentary_m2m_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='account_attribution',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='commentary_attribution',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='notes_attribution',
        ),
    ]
