# Generated by Django 3.1 on 2020-09-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_attribution_charfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='main_contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.writer'),
            preserve_default=False,
        ),
    ]
